stages:
  - build
  - deploy

cache:
  # key: $CI_COMMIT_REF_SLUG
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

build-game-job:
  stage: build
  image: node:16
  only:
    - master
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build:prod
  artifacts:
    paths:
      - build/

build-demo-job:
  stage: build
  image: node:16
  only:
    - demo
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build:dev
  artifacts:
    paths:
      - build/

#

deploy-game-job:
  stage: deploy
  environment: production
  resource_group: production
  only:
    - master
  image: mwienk/docker-git-ftp
  script:
    - git config git-ftp.url "ftp://$FTP_HOST/$FTP_PATH"
    - git config git-ftp.user "$FTP_USER"
    - git config git-ftp.password "$FTP_PASSWD"
    - git ftp push --verbose

deploy-game-build-job:
  stage: deploy
  environment: production
  resource_group: production
  only:
    - master
  image: mwienk/docker-lftp:latest
  dependencies:
    - build-game-job
  script:
    - lftp -e "set ftp:ssl-allow false; mirror -eRnv build $FTP_PATH/build; exit;" -u $FTP_USER,$FTP_PASSWD $FTP_HOST

deploy-demo-job:
  stage: deploy
  environment: staging
  resource_group: staging
  only:
    - demo
  image: mwienk/docker-git-ftp
  script:
    - git config git-ftp.url "ftp://$FTP_HOST/$FTP_PATH"
    - git config git-ftp.user $FTP_USER
    - git config git-ftp.password $FTP_PASSWD
    - git ftp push --verbose

deploy-demo-build-job:
  stage: deploy
  environment: staging
  resource_group: staging
  only:
    - demo
  image: mwienk/docker-lftp:latest
  dependencies:
    - build-demo-job
  script:
    - lftp -e "set ftp:ssl-allow false; mirror -eRnv build $FTP_PATH/build; exit;" -u $FTP_USER,$FTP_PASSWD $FTP_HOST
