# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

image: mwienk/docker-git-ftp

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

cache:
  paths:
    - node_modules/

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  only:
    - master
  # rules:
  #  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "branch $CI_COMMIT_BRANCH"
    - ls
    - apt-get update -qq
    - apt-get install -y -qq node npm
    - npm install
    - npm run build:dev

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - apt-get install -y -qq git-ftp
    - echo "Application successfully deployed."
